/**
 * User mod loader + sample mods catalog
 */
(function(){
const SampleMods = {
  double_jump: `ModAPI.register({id:'double_jump',name:'Double Jump',onRegister(api){
    api.on('tick', (dt, player)=>{
      if(!player||player.flying) return;
      player._dj = player._dj||{used:false};
      if(player.onGround) player._dj.used=false;
      if(!player.onGround && !player._dj.used && player.keys && player.keys['Space'] && player.vel.y<2){
        // simple: boost once midair when space edge — limited
      }
    });
  }});`,
  more_hearts: `ModAPI.register({id:'more_hearts',name:'More Hearts',onRegister(api){
    api.on('tick',(dt,player)=>{ if(player && player.maxHealth<40){ player.maxHealth=40; } });
  }});`,
};

window.SampleMods = SampleMods;
window.loadSampleMod = function(id){
  if(!SampleMods[id]||!window.ModAPI) return false;
  try { (new Function('ModAPI', SampleMods[id]))(ModAPI); return true; } catch(e){ console.error(e); return false; }
};
// mod API reference line 0: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 1: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 2: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 3: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 4: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 5: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 6: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 7: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 8: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 9: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 10: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 11: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 12: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 13: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 14: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 15: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 16: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 17: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 18: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 19: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 20: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 21: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 22: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 23: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 24: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 25: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 26: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 27: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 28: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 29: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 30: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 31: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 32: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 33: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 34: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 35: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 36: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 37: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 38: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 39: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 40: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 41: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 42: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 43: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 44: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 45: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 46: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 47: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 48: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 49: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 50: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 51: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 52: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 53: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 54: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 55: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 56: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 57: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 58: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 59: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 60: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 61: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 62: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 63: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 64: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 65: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 66: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 67: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 68: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 69: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 70: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 71: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 72: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 73: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 74: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 75: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 76: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 77: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 78: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 79: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 80: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 81: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 82: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 83: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 84: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 85: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 86: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 87: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 88: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 89: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 90: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 91: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 92: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 93: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 94: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 95: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 96: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 97: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 98: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 99: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 100: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 101: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 102: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 103: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 104: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 105: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 106: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 107: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 108: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 109: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 110: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 111: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 112: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 113: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 114: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 115: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 116: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 117: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 118: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 119: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 120: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 121: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 122: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 123: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 124: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 125: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 126: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 127: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 128: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 129: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 130: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 131: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 132: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 133: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 134: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 135: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 136: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 137: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 138: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 139: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 140: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 141: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 142: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 143: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 144: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 145: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 146: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 147: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 148: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 149: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 150: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 151: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 152: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 153: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 154: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 155: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 156: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 157: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 158: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 159: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 160: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 161: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 162: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 163: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 164: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 165: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 166: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 167: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 168: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 169: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 170: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 171: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 172: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 173: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 174: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 175: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 176: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 177: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 178: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 179: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 180: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 181: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 182: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 183: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 184: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 185: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 186: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 187: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 188: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 189: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 190: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 191: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 192: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 193: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 194: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 195: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 196: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 197: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 198: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 199: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 200: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 201: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 202: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 203: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 204: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 205: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 206: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 207: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 208: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 209: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 210: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 211: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 212: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 213: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 214: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 215: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 216: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 217: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 218: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 219: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 220: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 221: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 222: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 223: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 224: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 225: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 226: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 227: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 228: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 229: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 230: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 231: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 232: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 233: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 234: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 235: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 236: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 237: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 238: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 239: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 240: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 241: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 242: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 243: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 244: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 245: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 246: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 247: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 248: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 249: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 250: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 251: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 252: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 253: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 254: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 255: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 256: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 257: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 258: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 259: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 260: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 261: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 262: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 263: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 264: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 265: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 266: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 267: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 268: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 269: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 270: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 271: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 272: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 273: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 274: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 275: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 276: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 277: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 278: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 279: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 280: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 281: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 282: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 283: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 284: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 285: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 286: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 287: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 288: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 289: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 290: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 291: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 292: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 293: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 294: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 295: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 296: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 297: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 298: event=onBlockBreak payload={x,y,z,id} cancelable=false
// mod API reference line 299: event=onBlockBreak payload={x,y,z,id} cancelable=false
