services:
  - type: web
    name: minecraft-pivo
    runtime: node
    plan: free
    region: frankfurt
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
